apiVersion: apps/v1
kind: Deployment
metadata:
  name: ey-cart-deploy 
  namespace: shubha-ns
  labels:
    app: cart-app
spec: 
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector: 
    matchLabels:
      app: cart-web
  template: 
    metadata:
      labels:
        app: cart-web
    spec: 
      containers: 
        - name: ey-cart-container
          image: muralisocial123/flipkart-app-web:v1.1.0
          ports:
            - containerPort: 80

  