apiVersion: v1
kind: Pod
metadata:
  name: flower-web-app
  namespace: shubha-ns
  labels:
    app: flower-app
spec:
  containers:
    - name: flower-app-container
      image: shubha20/flower-web-app:v2.1.0
      ports:
        - containerPort: 3015